import { ShieldCheck, Fingerprint, FlaskConical, Eye } from "lucide-react";

const points = [
  { icon: ShieldCheck, title: "Tamper-resistant records", desc: "Once a lab result is registered, it cannot be silently altered." },
  { icon: Fingerprint, title: "Batch traceability", desc: "Every jar links back to a specific hive, harvest date, and beekeeper." },
  { icon: FlaskConical, title: "Laboratory verification", desc: "Independent quality testing backs every verified claim." },
  { icon: Eye, title: "Transparent provenance", desc: "The full hive-to-jar journey is visible, not just a logo on a label." },
];

export default function AboutPage() {
  return (
    <div className="mx-auto max-w-2xl px-5 py-14">
      <h1 className="font-display text-3xl">About HoneyChain</h1>
      <p className="mt-4 text-muted-foreground">
        HoneyChain is a Smart India Hackathon prototype demonstrating end-to-end honey traceability — from hive
        monitoring, through laboratory quality testing, to a blockchain-anchored record any consumer can verify.
      </p>
      <div className="mt-8 space-y-5">
        {points.map((p) => (
          <div key={p.title} className="flex gap-3">
            <p.icon className="mt-0.5 size-5 shrink-0 text-nature" />
            <div>
              <p className="font-semibold">{p.title}</p>
              <p className="text-sm text-muted-foreground">{p.desc}</p>
            </div>
          </div>
        ))}
      </div>
      <p className="mt-10 rounded-xl bg-muted p-4 text-xs text-muted-foreground">
        This is a demo application. Blockchain transactions shown are generated by a mock provider and clearly
        labeled as demo transactions — no real blockchain network is used. Laboratory grades use a prototype
        &quot;HoneyChain Demo Quality Grade&quot; and are not an official regulatory certification.
      </p>
    </div>
  );
}
